FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache openssl
COPY package*.json ./
RUN npm install --cache /tmp/npm-cache --legacy-peer-deps
COPY . .
RUN npx prisma generate
CMD ["npm", "run", "worker"]
